server:
 port: 3333

spring:
 application:
   name: CLOUD-API-GATEWAY
 main:
    web-application-type: reactive
 cloud:
    gateway:
      routes:
        - id: welcome-api
          uri: lb://WELCOME-API
          predicates:
           - Path=/welcome
        - id: greet-api
          uri: lb://GREET-API
          predicates:
           - Path=/greet
           